#include <stdio.h>
#include "mlogx.h"


int main()
{
    printf("Hello World!\n");
    CHECK_RET(mlogxByKey("test1", "hello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the worldhello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goo is goohello the world is goo %s %d\n", "nice day", 2000));
    CHECK_RET(mlogxByKey("test2", "hello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the worldhello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goo is goohello the world is goo %s %d\n", "nice day", 3000));
    CHECK_RET(mlogxByKey("test3", "hello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the worldhello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goohello the world is goo is goohello the world is goo %s %d\n", "nice day", 4000));
    mlogxShowKeys();
    mlogxShowKeysDetail();
    return 0;
}
